---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
    tag: latest

inputs:
  - name: pcf-pipelines
  - name: pivnet-product

outputs:
  - name: prepared-stemcell

run:
  path: pcf-pipelines/tasks/prepare-stemcell/task.sh
